
CREATE TABLE APP_USER(
    USER_ID BIGINT NOT NULL ,
    USER_NAME VARCHAR(36) NOT NULL,
    ENCRYPTED_PASSWORD VARCHAR(128) NOT NULL,
    ENABLED BIT NOT NULL
);

ALTER TABLE APP_USER ADD CONSTRAINT
APP_USER_PK PRIMARY KEY (USER_ID);

ALTER TABLE APP_USER ADD CONSTRAINT
APP_USER_UK unique (USER_NAME);

CREATE TABLE APP_ROLE(
    ROLE_ID BIGINT NOT NULL ,
    ROLE_NAME VARCHAR(30) NOT NULL
);

ALTER TABLE APP_ROLE ADD CONSTRAINT
APP_ROLE_PK PRIMARY KEY (ROLE_ID);

ALTER TABLE APP_ROLE ADD CONSTRAINT
APP_ROLE_UK UNIQUE (ROLE_NAME);

CREATE TABLE USER_ROLE
(
    ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL ,
    ROLE_ID BIGINT NOT NULL
);

alter table USER_ROLE
    add constraint USER_ROLE_PK primary key (ID);

alter table USER_ROLE
    add constraint USER_ROLE_UK unique (USER_ID, ROLE_ID);


ALTER TABLE USER_ROLE ADD CONSTRAINT
USER_ROLE_FK1 foreign key (USER_ID) REFERENCES APP_USER(USER_ID);

ALTER TABLE USER_ROLE ADD CONSTRAINT
USER_ROLE_FK2 FOREIGN KEY (ROLE_ID) REFERENCES APP_ROLE(ROLE_ID);

-- Used by Spring Remember Me API.
CREATE TABLE Persistent_Logins (

    username varchar(64) not null,
    series varchar(64) not null,
    token varchar(64) not null,
    last_used timestamp not null,
    PRIMARY KEY (series)

);
